name: "release"

on:
  push:
    branches: [master]

jobs:
  publish_release:
    uses: vodyani/workflows/.github/workflows/publish-release-v2.yml@master
    secrets:
      NPM_CI_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
      GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      ignore_build: true
